version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/kintun
            - ./logs:/kintun/logs
            - ./outputs:/kintun/outputs
        environment:
        - FLASK_DEBUG=1
        - PYTHONUNBUFFERED=notempty
        depends_on:
            - mongo
        networks:
            - mynetwork
        privileged: true

    mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      ports:
          - 27017:27017
      networks:
          - mynetwork

    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      depends_on:
        - mongo
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      networks:
          - mynetwork
          
      
networks:
  mynetwork:
    driver: bridge